spring.application.name=gestion-polizas

# Configuración de H2 en memoria
spring.datasource.url=jdbc:h2:mem:polizasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar Consola H2 para depuración
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Hibernate DDL Auto (creación de tablas automática)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL del Mock CORE
app.core-mock.url=http://localhost:8080/core-mock/evento

# Configuración de Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.example.gestionpolizas=DEBUG

# Monitoreo y Observabilidad con Azure Application Insights
spring.cloud.azure.monitor.connection-string=${APPLICATIONINSIGHTS_CONNECTION_STRING:}

